#include "slime.h"
#include "water_slime.h"
#include "fire_slime.h"
#include "three_slime.h"
#include "ice_slime.h"
#include "nut.h"
#include "meganut.h"

#include "human.h"
#include "wither.h"
#include "knight.h"
#include "archer.h"
#include "bishop.h"
#include "black_knight.h"
